// All dropdown options

export const CLIENTS = [
  'Western Union',
  'Workbox',
  'Truist',
];

export const SOURCES = [
  'Linkedin',
  'Naukri',
  'Referral',
  'Vendor',
  'Database',
];

export const YEARS = Array.from({length: 31}, (_, i) => (i).toString());
export const MONTHS = Array.from({length: 12}, (_, i) => (i).toString());
export const YEARS_PASS = Array.from({length: 30}, (_, i) => (2025 - i).toString());

export const SOURCER_NAMES = [
  'Internal',
  'Kairos',
  'Shejobs',
  'Madhees',
  'Innominds',
  'Vertex',
];

export const RECRUITERS = [
  'Kavya Adapala',
  'Sofia Safa',
  'Amulya Kanakanti',
  'Vommi Siva Sravani',
  'Mohana Sritanaya Ponnada',
  'Gannim Lalitha',
  'Sushma Malkapuram',
  'Anjali Goud',
  'Mohammad Fayaz',
  'Rachel Jyothi',
];

export const EMPLOYMENT_TYPES = [
  'Full Time',
  'Contract',
  'Intern',
];

export const ROLES = [
  'ETL Tester',
  'ETL Test Lead',
  'ETL Developer',
  'ETL Technical Lead',
  'Technical PM',
  'Cloud DevOps Engineer',
  'Matillion Developer',
  'Sr. Data Engineers (Talend)',
  'Sr. Data Engineers (Abinitio)',
  'Sr. QA Engineers',
  'Tech Lead with ETL experience (Senior Resource)',
  'PKWARE Data Scanning and Classification',
  'Cyera Data Scanning and Classification',
  'Ataccama Data Quality',
  'Talend',
  'Matillion',
  'Alteryx Server',
  'SAS Viya Cloud',
  'Neo4j',
  'Enterprise Snowflake',
  'Data Engineers (Graph Developer, ETL and UI)',
  'Linux Admin',
  'ML Testing',
  'Alteryx Developer',
  'Python Developer',
  'Data Engineer - Talend with API',
  'Digital Quality Assurance Engineer',
  'Data Analyst (MDM , Reltio)',
  'Senior Talend Data Engineer',
  'Project Manager',
  'Data Modeler',
  'Control Testing Analysts',
  'Data Analysts',
  'PKWare Data Scan Specialists',
  'Data Analyst - SAS',
  'Informatica Developer',
  'Talend Lead',
  'Tester',
  'Tableau Developers',
  'Qlik Developers',
  'Data Governance Specialist',
  'SAS Monitoring Code Compliance Engineer',
  'Data Engineer - Talend & Snowflake',
  'SAS Code Modernization',
  'SAS Automation Implementers',
  'Migration Test Engineers',
  'Cloud Devops(SAS)',
  'CI-CD Devops',
  'Snowflake Developer',
  'Scrum Master',
  'Senior Talend Developer',
  'Talend Support',
  'Salesforce Developer',
  'Technical Project Managers',
  'Power BI Admin + Alteryx',
  'SFMC Developer',
  'Hadoop Admin',
  'SFMC Lead',
  'DB Developers - UCD',
  'DB Lead - E1',
];

export const WORK_FROM_OFFICE = [
  'Yes',
  'No',
];

export const EDUCATION = [
  '10th Pass / SSC / Matriculation',
  '12th Pass / HSC / Intermediate / PUC',
  'ITI / NCVT / Trade Certificate',
  'Polytechnic Diploma',
  'Diploma in Engineering',
  'Diploma in Computer Applications',
  'Diploma in Hotel Management',
  'Diploma in Fashion Designing',
  'Diploma in Education (D.Ed.)',
  'B.A. (Bachelor of Arts)',
  'B.Sc. (Bachelor of Science)',
  'B.Com. (Bachelor of Commerce)',
  'BBA (Bachelor of Business Administration)',
  'BBM (Bachelor of Business Management)',
  'BMS (Bachelor of Management Studies)',
  'BCA (Bachelor of Computer Applications)',
  'B.E. (Bachelor of Engineering)',
  'B.Tech (Bachelor of Technology)',
  'B.Arch (Bachelor of Architecture)',
  'B.Pharm (Bachelor of Pharmacy)',
  'B.Ed. (Bachelor of Education)',
  'LLB (Bachelor of Law)',
  'BDS (Bachelor of Dental Surgery)',
  'MBBS (Bachelor of Medicine and Surgery)',
  'BFA (Bachelor of Fine Arts)',
  'BSW (Bachelor of Social Work)',
  'M.A. (Master of Arts)',
  'M.Sc. (Master of Science)',
  'M.Com. (Master of Commerce)',
  'MBA (Master of Business Administration)',
  'PGDM (Post Graduate Diploma in Management)',
  'MCA (Master of Computer Applications)',
  'M.E. (Master of Engineering)',
  'M.Tech (Master of Technology)',
  'M.Pharm (Master of Pharmacy)',
  'M.Ed. (Master of Education)',
  'LLM (Master of Law)',
  'M.Arch (Master of Architecture)',
  'MSW (Master of Social Work)',
  'Ph.D. (Doctor of Philosophy)',
  'M.Phil. (Master of Philosophy)',
  'D.Sc. (Doctor of Science)',
  'D.Litt. (Doctor of Literature)',
  'CA (Chartered Accountant)',
  'CS (Company Secretary)',
  'CMA / ICWA (Cost and Management Accountant)',
  'CFA (Chartered Financial Analyst)',
  'ACCA',
  'PMP (Project Management Professional)',
  'Six Sigma Certification (Green Belt / Black Belt)',
  'AWS Certification',
  'Azure Certification',
  'Google Cloud Certification',
  'Data Science Certification',
  'Artificial Intelligence / Machine Learning Certification',
  'Digital Marketing Certification',
  'SAP Certification',
  'ERP Certification',
  'CCNA / CCNP (Cisco)',
  'MCSA / MCSE (Microsoft)',
  'Oracle Certification',
  'Java Certification',
  'Python Certification',
  'Full Stack Developer Certification',
  'NIOS (National Institute of Open Schooling)',
  'IGNOU Degree',
  'YCMOU Degree',
  'Distance Education Degree',
  'Foreign Degree (recognized by AIU/UGC)',
  'MOOC Certification (Coursera, edX, Udemy, etc.)',
  'Skill India / NSDC Certification',
  'Apprenticeship Training',
  'Internship Completion',
];

export const PREFERRED_LOCATIONS = [
  'Hyderabad',
  'Bangalore',
  'Chennai',
  'Anywhere India',
];

export const SCREENING = [
  'Shortlisted',
  'Rejected',
  'Yet to screen',
  'Duplicate',
];

export const HACKERRANK_ASSESSMENT = [
  'Required',
  'Not Required',
];

export const L1_STATUS = [
  'Shortlisted',
  'Rejected',
  'Scheduled',
  'Yet to Schedule',
];

export const L1_PANEL_NAMES = [
  'Venkateswar Reddy Janke',
  'Prathyusha Mande',
  'Balakrishna N',
  'Venkata Sairan Muvalla',
  'Sudheer kumar Kandula',
  'Anil Mathew',
  'Yenduva Venkata Mukesh Naidu',
  'Maru Subba reddy',
  'Michael Sauddin',
  'Siva ram Prasad Pilla',
  'Sriram Kumar madu',
  'Vijay Kumar Settybalija',
  'Chiranjeevi Kuracha',
  'Pradeep Somarajulu',
  'Naveen Chinde',
  'Prasanth Settipalli',
  'Purna Chander Racha',
  'Mohammad Shadab Kattubadi',
  'Olufemi Adegbesan',
  'Kranthi Kiran Parasu',
  'Venkata Ramana Gingupalli',
  'Manogna Muchala',
  'Srinu Yenuganti',
  'Veerababu Velpuri',
  'Ranganath Dindukurthi',
  'Saravana Kumar Kutuva Mohan',
  'chendra Gadde',
  'Abhilash Sadanand Pattar',
  'Hima bindu Ganta',
  'Deepika Chintalapally',
  'Lakshmi Koya',
  'Bhagyashree Kalluri',
  'Satya Narayana Bitra',
  'Vasam raj kumar',
  'Sowjanya Reddy Kondam',
  'Bala Murugan',
  'Bharat Jamboju',
  'Atul Gupta',
  'Karthik Annadevara',
  'Narendra Bollineni',
  'Praneeth Kumar P',
  'vikram Thakur',
  'Raya Santhosh Kumar',
  'Munavvar Mirza',
  'Nagasai Harish Prasad Gandham',
  'Mulinti sai reddy',
  'Jwala pogula',
  'Ashok Goud',
  'Pruthvi pendhota',
  'Hukum chandu Rokkala'
];

export const L2_STATUS = [
  'Shortlisted',
  'Rejected',
  'Scheduled',
  'Yet to Schedule',
];

export const L2_PANEL_NAMES = [
  'Venkateswar Reddy Janke',
  'Prathyusha Mande',
  'Balakrishna N',
  'Venkata Sairan Muvalla',
  'Sudheer kumar Kandula',
  'Anil Mathew',
  'Yenduva Venkata Mukesh Naidu',
  'Maru Subba reddy',
  'Michael Sauddin',
  'Siva ram Prasad Pilla',
  'Sriram Kumar madu',
  'Vijay Kumar Settybalija',
  'Chiranjeevi Kuracha',
  'Pradeep Somarajulu',
  'Naveen Chinde',
  'Prasanth Settipalli',
  'Purna Chander Racha',
  'Mohammad Shadab Kattubadi',
  'Olufemi Adegbesan',
  'Kranthi Kiran Parasu',
  'Venkata Ramana Gingupalli',
  'Manogna Muchala',
  'Srinu Yenuganti',
  'Veerababu Velpuri',
  'Ranganath Dindukurthi',
  'Saravana Kumar Kutuva Mohan',
  'chendra Gadde',
  'Abhilash Sadanand Pattar',
  'Hima bindu Ganta',
  'Deepika Chintalapally',
  'Lakshmi Koya',
  'Bhagyashree Kalluri',
  'Satya Narayana Bitra',
  'Vasam raj kumar',
  'Sowjanya Reddy Kondam',
  'Bala Murugan',
  'Bharat Jamboju',
  'Atul Gupta',
  'Karthik Annadevara',
  'Narendra Bollineni',
  'Praneeth Kumar P',
  'vikram Thakur',
  'Raya Santhosh Kumar',
  'Munavvar Mirza',
  'Nagasai Harish Prasad Gandham',
  'Mulinti sai reddy',
  'Jwala pogula',
  'Ashok Goud',
  'Pruthvi pendhota',
  'Hukum chandu Rokkala'
];

export const L3_STATUS = [
  'Shortlisted',
  'Rejected',
  'Scheduled',
  'Yet to Schedule',
];

export const L3_PANEL_NAMES = [
  'Venkateswar Reddy Janke',
  'Prathyusha Mande',
  'Balakrishna N',
  'Venkata Sairan Muvalla',
  'Sudheer kumar Kandula',
  'Anil Mathew',
  'Yenduva Venkata Mukesh Naidu',
  'Maru Subba reddy',
  'Michael Sauddin',
  'Siva ram Prasad Pilla',
  'Sriram Kumar madu',
  'Vijay Kumar Settybalija',
  'Chiranjeevi Kuracha',
  'Pradeep Somarajulu',
  'Naveen Chinde',
  'Prasanth Settipalli',
  'Purna Chander Racha',
  'Mohammad Shadab Kattubadi',
  'Olufemi Adegbesan',
  'Kranthi Kiran Parasu',
  'Venkata Ramana Gingupalli',
  'Manogna Muchala',
  'Srinu Yenuganti',
  'Veerababu Velpuri',
  'Ranganath Dindukurthi',
  'Saravana Kumar Kutuva Mohan',
  'chendra Gadde',
  'Abhilash Sadanand Pattar',
  'Hima bindu Ganta',
  'Deepika Chintalapally',
  'Lakshmi Koya',
  'Bhagyashree Kalluri',
  'Satya Narayana Bitra',
  'Vasam raj kumar',
  'Sowjanya Reddy Kondam',
  'Bala Murugan',
  'Bharat Jamboju',
  'Atul Gupta',
  'Karthik Annadevara',
  'Narendra Bollineni',
  'Praneeth Kumar P',
  'vikram Thakur',
  'Raya Santhosh Kumar',
  'Munavvar Mirza',
  'Nagasai Harish Prasad Gandham',
  'Mulinti sai reddy',
  'Jwala pogula',
  'Ashok Goud',
  'Pruthvi pendhota',
  'Hukum chandu Rokkala'
];

export const MANAGERIAL_STATUS = [
  'Shortlisted',
  'Rejected',
  'Scheduled',
  'Yet to Schedule',
];

export const HR_NAMES = [
  "Mounika Chodisetti",
  "Sindhuja Junnuru",
  "Srinivas T P",
  "Suvva Srideep",
];

export const HR_STATUS = [
  'Shortlisted',
  'Rejected',
  'Scheduled',
  'Yet to Schedule',
];

export const NOTICE_PERIOD = [
  "Immediate",
  "15 Days",
  "1 Month",
  "2 Months",
  "3 Months"
];

export const APPROVED_BY_RAJ = [
  'Shortlisted',
  'Rejected',
  'Scheduled',
  'Yet to Schedule',
];

export const FINAL_STATUS = [
  'L1 scheduled',
  'L1 Select',
  'L1 Reject',
  'L2 scheduled',
  'L2 Select',
  'L2 Reject',
  'L3 Select',
  'L3 Reject',
  'Manager Select',
  'Manager Reject',
  'Client Select',
  'Client Reject',
  'HR Reject',
  'HR Select',
  'In Progress',
  'Feedback Pending',
  'Hold',
  'Interview Drop',
  'Final Select',
  'Pre offer drop',
  'Pending salary approval',
  'Checklist Raised',
  'Offer released',
  'Accepted',
  'Offer Accepted/Backoff',
  'Joined',
  'Yet To Join'
];
